openapi: 3.0.0
info:
  title: Multi-Agent System API
  description: API for interacting with specialized AI agents for book generation and RAG
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server

paths:
  /agents/research:
    post:
      summary: Execute Research Agent
      description: Use the Research Agent to gather accurate, verifiable information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The research query or topic
                  example: "Research ROS 2 navigation stack"
                context:
                  type: string
                  description: Context for the research (e.g., chapter topic)
                  example: "Chapter on robot navigation"
                parameters:
                  type: object
                  description: Additional parameters for the research
      responses:
        '200':
          description: Research results
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  result:
                    type: object
                    description: Research findings
                  sources:
                    type: array
                    items:
                      type: string
                    description: List of sources used

  /agents/writer:
    post:
      summary: Execute Writer Agent
      description: Use the Writer Agent to generate chapter content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                outline:
                  type: array
                  items:
                    type: string
                  description: Outline for the content to be generated
                context:
                  type: string
                  description: Context for the writing (e.g., module focus)
                user_profile:
                  $ref: '#/components/schemas/UserProfile'
                parameters:
                  type: object
                  description: Additional parameters for the writing
      responses:
        '200':
          description: Generated content
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  content:
                    type: string
                    description: Generated content in Markdown format
                  quality_score:
                    type: number
                    description: Quality assessment score (0-100)

  /agents/editor:
    post:
      summary: Execute Editor Agent
      description: Use the Editor Agent to improve existing content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Content to be edited
                editing_focus:
                  type: array
                  items:
                    type: string
                    enum: [grammar, structure, clarity, technical_accuracy, consistency]
                  description: Aspects to focus on during editing
                user_profile:
                  $ref: '#/components/schemas/UserProfile'
                parameters:
                  type: object
                  description: Additional parameters for the editing
      responses:
        '200':
          description: Edited content
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  content:
                    type: string
                    description: Edited content in Markdown format
                  changes_summary:
                    type: string
                    description: Summary of changes made
                  quality_score:
                    type: number
                    description: Quality assessment score (0-100)

  /agents/rag-engineer:
    post:
      summary: Execute RAG Engineer Agent
      description: Use the RAG Engineer Agent for RAG system tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  enum: [create_embedding_pipeline, optimize_chunking, design_schema, build_retrieval_logic]
                  description: The RAG engineering task to perform
                parameters:
                  type: object
                  description: Parameters specific to the task
      responses:
        '200':
          description: RAG engineering result
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  result:
                    type: object
                    description: Result of the RAG engineering task
                  code:
                    type: string
                    description: Generated code or configuration

  /agents/developer:
    post:
      summary: Execute Developer Agent
      description: Use the Developer Agent to generate code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requirements:
                  type: string
                  description: Description of what code needs to be generated
                language:
                  type: string
                  description: Programming language for the code
                context:
                  type: string
                  description: Context for the code generation
                parameters:
                  type: object
                  description: Additional parameters for code generation
      responses:
        '200':
          description: Generated code
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  code:
                    type: string
                    description: Generated code
                  quality_score:
                    type: number
                    description: Quality assessment score (0-100)

  /agents/documentation:
    post:
      summary: Execute Documentation Agent
      description: Use the Documentation Agent to generate documentation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content_type:
                  type: string
                  enum: [tutorial, api_reference, guide, architecture_diagram]
                  description: Type of documentation to generate
                subject:
                  type: string
                  description: Subject of the documentation
                context:
                  type: string
                  description: Context for the documentation
                parameters:
                  type: object
                  description: Additional parameters for documentation
      responses:
        '200':
          description: Generated documentation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  documentation:
                    type: string
                    description: Generated documentation in Markdown format
                  quality_score:
                    type: number
                    description: Quality assessment score (0-100)

  /agents/planner:
    post:
      summary: Execute Project Planner Agent
      description: Use the Project Planner Agent to break tasks into steps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  description: The task to be planned
                context:
                  type: string
                  description: Context for the planning
                parameters:
                  type: object
                  description: Additional parameters for planning
      responses:
        '200':
          description: Generated plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Request ID
                  status:
                    type: string
                    enum: [PENDING, PROCESSING, COMPLETED, FAILED]
                  plan:
                    type: object
                    description: Generated project plan with steps, milestones, and dependencies
                  next_steps:
                    type: array
                    items:
                      type: string
                    description: Actionable next steps

  /rag/query:
    post:
      summary: Query RAG System
      description: Ask questions to the RAG-based chatbot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's question
                session_id:
                  type: string
                  description: Session ID for maintaining conversation context
                user_id:
                  type: string
                  description: User ID for personalized responses
                parameters:
                  type: object
                  description: Additional query parameters
      responses:
        '200':
          description: RAG response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Query ID
                  response:
                    type: string
                    description: The RAG system's answer
                  sources:
                    type: array
                    items:
                      type: string
                    description: Document IDs used to generate the response
                  confidence_score:
                    type: number
                    description: Confidence in response accuracy (0-100)

components:
  schemas:
    UserProfile:
      type: object
      properties:
        user_id:
          type: string
          description: Unique identifier for the user
        experience_level:
          type: string
          enum: [BEGINNER, INTERMEDIATE, EXPERT]
          description: User's experience level
        technical_background:
          type: string
          description: User's technical background
        preferred_difficulty:
          type: string
          enum: [EASY, MEDIUM, HARD]
          description: Preferred difficulty level
        learning_goals:
          type: array
          items:
            type: string
          description: User's learning goals
        hardware_access:
          type: array
          items:
            type: string
          description: Hardware access (e.g., Jetson, GPU, Cloud)
        language_preference:
          type: string
          description: Preferred language for responses